name: Android Cloud Phone (VNC + Tailscale)

on:
  workflow_dispatch:

jobs:
  android-cloud-vnc:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip qemu-kvm libvirt-daemon-system libvirt-clients \
          bridge-utils xvfb x11vnc socat openjdk-11-jdk curl git

      - name: Setup Android SDK
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools
          cd $HOME/android-sdk/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O tools.zip
          unzip -q tools.zip
          rm tools.zip
          mv cmdline-tools latest

          echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
          echo "$HOME/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "$HOME/android-sdk/platform-tools" >> $GITHUB_PATH
          echo "$HOME/android-sdk/emulator" >> $GITHUB_PATH

      - name: Install SDK components
        run: |
          sdkmanager --sdk_root=$HOME/android-sdk --licenses <<< "y"
          sdkmanager --sdk_root=$HOME/android-sdk \
            "platform-tools" "platforms;android-30" \
            "system-images;android-30;google_apis;x86_64" "emulator"

      - name: Create & start Android emulator
        run: |
          echo "no" | avdmanager create avd -n test -k "system-images;android-30;google_apis;x86_64" --device "pixel"

          # Start a virtual display
          Xvfb :1 -screen 0 1080x1920x24 &
          export DISPLAY=:1

          # Boot the emulator headless
          nohup emulator -avd test -noaudio -no-boot-anim -gpu swiftshader_indirect -no-window &
          echo "Waiting for emulator to boot..."
          adb wait-for-device
          sleep 30
          adb shell input keyevent 82

      - name: Install & start Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=android-runner-${GITHUB_RUN_ID}

      - name: Start VNC server
        run: |
          export DISPLAY=:1
          x11vnc -display :1 -passwd android123 -forever -shared -bg
          echo "VNC_PASSWORD=android123" >> $GITHUB_ENV
          sleep 10

      - name: Show connection info
        run: |
          TAILSCALE_IP=$(tailscale ip -4)
          echo "======================================="
          echo "✅ Android emulator is running!"
          echo "Connect using a VNC client with:"
          echo "IP: $TAILSCALE_IP"
          echo "Port: 5900"
          echo "Password: $VNC_PASSWORD"
          echo "======================================="
          while true; do sleep 300; done
